spring:
  datasource:
    url: jdbc:h2:mem:products
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true

server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true

keycloak:
  url: http://localhost:8080
  realm: test
  jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
